### ISSUE TITLE
extra DB queries

### ISSUE THREAD

**Issue by groenewege** [spatie/laravel-medialibrary#22]
Hello,

I love this package but I encounter a little performance problem. 
I don't know if it is my doing or a bug in the package.

I have the impression that for every media image that I display an extra DB query is executed requesting all columns from the parent model item. (see debug bar queries in attached image)

![queries](https://cloud.githubusercontent.com/assets/645870/8711354/7027637e-2b51-11e5-9139-dfaf345dde11.png)

In my app I do the following : 

- I request a collection of items. i.e. `$photos = repo->all();`
- I lazy load the media objects attached to the items. i.e. `$photos->load("media");`
- When I loop over the items, I see a DB query for all columns for every item. i.e. `SELECT * FROM photos WHERE id = 1`

**Comment by freekmurze** [comment]
That's not so good. I'll investigate this in the coming days. If the problem is caused by the medialibrary, rest assured that it will be fixed soon.

**Comment by groenewege** [comment]
Thank you.

For your information : each time I use the `getFirstMediaURL` method to see if an image is attached to the model object and then I use the `getFirstMediaURL` method again to display that image.

**Comment by freekmurze** [comment]
I tried to reproduce your problem, but I wasn't able to do so.

This piece of code
```php
        $this->testModelWithConversion->addMedia($this->getTestFilesDirectory('test.jpg'));

        \DB::connection()->enableQueryLog();

        $testModels = $this->testModelWithConversion->with('media')->get();

        $testModels[0]->getFirstMediaUrl();
        $testModels[0]->getFirstMediaUrl();
        $testModels[0]->getFirstMediaUrl();
        $testModels[0]->getFirstMediaUrl();

        dd(\DB::getQueryLog());
    }
```
results in only two queries being logged. This looks fine to me.

If also added an alternative version of this test to the package. Take a look at it [here](https://github.com/spatie/laravel-medialibrary/blob/master/tests/Performance/PerformanceTest.php).

Could you please give some more instructions on how to recreate the problem?

**Comment by groenewege** [comment]
Thank you for taking the time to investigate this issue.

I have been tinkering a bit and I noticed that I don't get the extra queries when I use the getFirstMediaUrl method without parameters : 

```
$this->getFirstMediaURL()
```

But I see the extra queries when I use parameters to target a specific collection and conversion :

```
$this->getFirstMediaURL('hero_image', 'hero')
```

I hope this helps.

**Comment by freekmurze** [comment]
I found the problem and fixed in dev-master. Could you try it out before I tag a new version?

**Comment by groenewege** [comment]
Thank you for addressing this issue !

I see less DB queries after updating to the latest version.

Although, they have not all disappeared.

i.e. in the example form my first comment I still see 2 from the 3 `SELECT * FROM ...` queries.

- a query for all the information from the page when I display the hero image of the page : `$this->getFirstMediaURL('hero_image', 'hero')`
- a query for all the information from the first gallery image when I display the first gallery image : `$this->getFirstMediaURL('gallery_image', 'thumbnail')`
- the query for all the information of the second gallery image does no longer appear in the query log.

![db](https://cloud.githubusercontent.com/assets/645870/8893111/b50972be-3382-11e5-8b5b-9e9448a4347a.png)

Is it necessary to make at least one query for all information from a parent model of a media object ?
Is it necessary to make this query a `SELECT * FROM ...` query ?

I am sorry that I can't help more with finding  a solution, I really appreciate all your work.

**Comment by freekmurze** [comment]
A new version of the solution is now available in dev-master. Internally the package will now not go to the db to fetch the conversions of the parent model. 

Could you update to the latest master version and try again?

**Comment by groenewege** [comment]
:smiley: 

I think all the extra queries are gone. 
The number of DB queries are divided by 2 on my pages.
Thank you very much. 

I owe you a :beer: if we run into each other at a conference or meetup.

**Comment by freekmurze** [comment]
Thanks for reporting the issue! The newly tagged version 2.2.1 includes the fix.

:smiley: If you are going to Laracon this year I might take you up on that :beer:  :
