### ISSUE TITLE
php artisan medialibrary:regenerate runs out of memory

### ISSUE THREAD

**Issue by pamo85** [spatie/laravel-medialibrary#34]
while regenerating many images it never releases memory so it runs out.
please release used memory after each images.

**Comment by pamo85** [comment]
same issue when I bulkinsert many new images.

**Comment by freekmurze** [comment]
Could you tell me what sort of images you are trying to process and which conversionProfiles you are using. Tell me anything that helps me recreate the problem.

If you can spot a problem in the code, you're welcome to submit a PR to fix it.

**Comment by pamo85** [comment]
on my testsystem i only have jpegs. but I will proceed all kind f images.

that's my conersion settings.

        $this->addMediaConversion('thumb')
            ->setManipulations(['w' => 158, 'h' => 158, 'fit' => 'crop'])
            ->performOnCollections('images');

        $this->addMediaConversion('thumb@2x')
            ->setManipulations(['w' => 312, 'h' => 312, 'fit' => 'crop'])
            ->performOnCollections('images');

        $this->addMediaConversion('header')
            ->setManipulations(['w' => 400, 'h' => 800, 'fit' => 'crop'])
            ->performOnCollections('images');

        $this->addMediaConversion('header@2x')
            ->setManipulations(['w' => 800, 'h' => 1600, 'fit' => 'crop'])
            ->performOnCollections('images');

        $this->addMediaConversion('square')
            ->setManipulations(['w' => 800, 'h' => 800, 'fit' => 'crop'])
            ->performOnCollections('images');

        $this->addMediaConversion('square@2x')
            ->setManipulations(['w' => 1600, 'h' => 1600, 'fit' => 'crop'])
            ->performOnCollections('images');

but I don't think the type of images is a problem.

I think it's in laravel-medialibrary/src/FileManipulator.php


    /**
     * Perform the conversion.
     *
     * @param \Spatie\MediaLibrary\Media $media
     * @param Conversion                 $conversion
     * @param string                     $copiedOriginalFile
     *
     * @return string
     */
    public function performConversion(Media $media, Conversion $conversion, $copiedOriginalFile)
    {
        $conversionTempFile = pathinfo($copiedOriginalFile, PATHINFO_DIRNAME).'/'.string()->random(16).
            $conversion->getName().'.'.$media->extension;
        File::copy($copiedOriginalFile, $conversionTempFile);
        foreach ($conversion->getManipulations() as $manipulation) {
            (new GlideImage())
                ->load($conversionTempFile, $manipulation)
                ->useAbsoluteSourceFilePath()
                ->save($conversionTempFile);
        }
        return $conversionTempFile;
    }

in this part you do conversions. it allocates memory for the GlideImage object but it never releases memory. usually it's not a problem because memory will released after the script ends. but in case ofbulkinserts or on regenerate you may have hundrets of images and they'll allocate a lot of memory before script ends.

I think we should release memory after ->save(). I'll try something later today. i think there should be a soloution in glide or with unset() in native php.

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention. Like mentioned in your PR, this issue was caused by a memory leak in the underlying [spatie/laravel-glide package](https://github.com/spatie/laravel-glide). It has been solved there. Just make sure you have version 2.2.5 of that package installed.

**Comment by mahony0** [comment]
Similar issue is still persist for me. My model has conversions:

```php
public function registerMediaConversions()
    {
        $this->addMediaConversion('default')
            ->setManipulations([
                'w' => 82, 'h' => 82,
                'fit' => 'contain',
                'q' => '90'
            ])
            ->performOnCollections('officelogo');

        $this->addMediaConversion('default')
            ->setManipulations([
                'w' => 1140, 'h' => 318,
                'fit' => 'contain',
                'q' => '90'
            ])
            ->performOnCollections('officebanner');
    }
```

I changed memory limit temporarily to 128MB and when i run command, it gives me following error after 3rd conversion:

> Media 1 regenerated
Media 2 regenerated
Media 6 regenerated
[Symfony\Component\Debug\Exception\FatalErrorException]
Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)


What I should to do about this?

**Comment by freekmurze** [comment]
I'm having no problem converting an entire large medialibrary with this command. Behind the scenes gd or imagick is used so maybe the high memory usage happens there. Changing PHP's memory limit will not help in that case.

Are you running this by any chance on a droplet with only 512MB of RAM. In that case, try adding a little bit of swap to see if that helps.

**Comment by mahony0** [comment]
I have tested this on our production server which has enough capacity for swap and memory (32gb)

It seems we are getting problem with GD:
> [2016-05-25 08:52:57] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes) in /PATH/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php:32

**Comment by mahony0** [comment]
btw, next image after getting error is a little big like 5000x4000 and 900kb. Maybe it's the problem for conversions?

**Comment by freekmurze** [comment]
It's possible that there is a memory leak with GD / Imagick. I'll try to debug this soon.
In the meantime you could try performing all conversions seperately on a queue. This will convert each image in their seperate PHP process and avoid memory leaks.

**Comment by t0n1zz** [comment]
hello i just now get this error too
Allowed memory size of 134217728 bytes exhausted (tried to allocate 56819713 bytes)

just running it on laravel valet with default configuration.

and i enabled withResponsiveImages and also add this into my model

public function registerMediaCollections()
    {
        $this->addMediaCollection('admin_foto')
            ->singleFile()
            ->registerMediaConversions(function(Media $media){
                $this->addMediaConversion('thumb')
                    ->width(50)
                    ->height(50);
            });
    }
i tried to upload images taken from my iphone 5c with total size 1.2mb... any idea why? i am not testing it on production server yet since the overall development not done yet..
